### PR TITLE
Oauth

### PR DESCRIPTION
**Pull request by radeklos**
oauth using django-allauth.

### CODE REVIEW

**Comment by radeklos** [comment]
@peeklondon @krak3n CR please.

**Comment by krak3n** [comment]
Is this intended to also handle general authentication?

**Comment by krak3n** [comment]
Will it be our session store?

**Comment by radeklos** [comment]
It could be. Unfortunately djagno forces us to store session there.. But we can store token wherever we want. Authentication and authorisation are already implemented in djagno and djago rest framework so I'm using them here.

**Comment by krak3n** [comment]
Ok, i mean if this system can handle it all cleanly there is no need for a separate auth service for users. :smile:

**Comment by radeklos** [comment]
We can have auth service later on just for a 'token storage' to better service scaling but I think that this is ok for now.

**Pull request merged**
